"""Deterministic Agent 17 orchestration loop."""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass
from datetime import UTC, datetime
from hashlib import sha256
from typing import Any

from app.agent.logger import LoopLogger
from app.agent.loop_state import LoopState, LoopStatus, LoopStep, utc_timestamp
from app.agent.retry import FailureType, RetryPolicy, classify_failure
from app.agent.schemas import AgentResult, ReflectionResult
from app.evaluation.models import EvaluationResult
from app.execution.models import ExecutionReport, ExecutionStatus, ExecutionTask
from app.execution.runner import run_plan
from app.feedback import FeedbackEngine, FeedbackSignal
from app.memory.service import MemoryService
from app.planning.models import Adaptation
from app.planning import build_execution_plan, plan as plan_task
from app.planning.conflict_resolver import ConflictResolver
from app.self_improvement.engine import SelfImprovementEngine

SUCCESS = "success"
PARTIAL = "partial"
FAILURE = "failure"


@dataclass(frozen=True, slots=True)
class _PlanContext:
    plan: Any
    resolved_adaptation_count: int


class AgentLoop:
    """Orchestrates plan, execute, validate, reflect, and persist steps."""

    def __init__(
        self,
        memory_service: MemoryService | None = None,
        self_improvement_engine: SelfImprovementEngine | None = None,
        feedback_engine: FeedbackEngine | None = None,
        conflict_resolver: ConflictResolver | None = None,
        retry_policy: RetryPolicy | None = None,
        loop_logger: LoopLogger | None = None,
        now_fn: Callable[[], datetime] | None = None,
    ) -> None:
        if now_fn is None:
            raise ValueError("now_fn must be provided for deterministic execution")
        self._now_fn = now_fn
        self._memory = memory_service or MemoryService(now_fn=self._now_fn)
        if hasattr(self._memory, "set_now_fn"):
            self._memory.set_now_fn(self._now_fn)
        self._conflict_resolver = conflict_resolver or ConflictResolver()
        self._retry_policy = retry_policy or RetryPolicy(max_attempts=3)
        self._loop_logger = loop_logger or LoopLogger(now_fn=self._now_fn)
        self._feedback_engine = feedback_engine or FeedbackEngine(now_fn=self._now_fn)
        self._state_history: list[LoopState] = []
        self._last_iteration_id = ""

        if self_improvement_engine is not None:
            self._self_improvement = self_improvement_engine
        elif isinstance(self._memory, MemoryService):
            self._self_improvement = SelfImprovementEngine()
        else:
            self._self_improvement = None

    @property
    def state_history(self) -> tuple[LoopState, ...]:
        """Immutable state history for the most recent run."""
        return tuple(self._state_history)

    @property
    def loop_logs(self) -> tuple[dict[str, Any], ...]:
        """Immutable structured logs for the most recent run."""
        return self._loop_logger.entries

    @property
    def last_iteration_id(self) -> str:
        """Last deterministic iteration ID generated by run."""
        return self._last_iteration_id

    @staticmethod
    def deterministic_iteration_id(goal: str) -> str:
        """Compute reproducible iteration ID from normalized goal text."""
        normalized = goal.strip()
        digest = sha256(normalized.encode("utf-8")).hexdigest()
        return f"iter-{digest[:16]}"

    def run(self, goal: str) -> AgentResult:
        """Run the deterministic agent loop for a single goal string."""
        normalized_goal = goal.strip()
        if not normalized_goal:
            raise ValueError("goal must be a non-empty string")

        self._state_history = []
        self._last_iteration_id = self.deterministic_iteration_id(normalized_goal)

        plan_context = self._run_step_with_retry(
            iteration_id=self._last_iteration_id,
            step=LoopStep.PLAN,
            operation=lambda: self._plan(normalized_goal),
        )
        execution_report = self._run_step_with_retry(
            iteration_id=self._last_iteration_id,
            step=LoopStep.EXECUTE,
            operation=lambda: self._execute(plan_context.plan),
        )
        metrics, status, evaluation_result, feedback_signal = self._run_step_with_retry(
            iteration_id=self._last_iteration_id,
            step=LoopStep.VALIDATE,
            operation=lambda: self._validate(execution_report),
        )
        reflection = self._run_step_with_retry(
            iteration_id=self._last_iteration_id,
            step=LoopStep.REFLECT,
            operation=lambda: self._reflect_step(
                goal=normalized_goal,
                plan=plan_context.plan,
                metrics=metrics,
                evaluation_result=evaluation_result,
                feedback_signal=feedback_signal,
                status=status,
                resolved_adaptation_count=plan_context.resolved_adaptation_count,
            ),
        )

        return AgentResult(
            goal=normalized_goal,
            status=status,
            plan=plan_context.plan,
            execution=execution_report,
            reflection=reflection,
        )

    def _run_step_with_retry(
        self,
        *,
        iteration_id: str,
        step: LoopStep,
        operation,
    ):
        attempt = 1
        while True:
            self._record_state(iteration_id, step, LoopStatus.STARTED, attempt)
            try:
                result = operation()
                duration_ms = 0
                self._record_state(iteration_id, step, LoopStatus.SUCCESS, attempt)
                self._loop_logger.emit_step(
                    iteration_id=iteration_id,
                    step=step,
                    status=LoopStatus.SUCCESS,
                    attempt=attempt,
                    duration_ms=duration_ms,
                    error_type=None,
                )
                return result
            except Exception as exc:
                duration_ms = 0
                failure_type = classify_failure(exc)

                self._record_state(iteration_id, step, LoopStatus.FAILED, attempt)
                self._loop_logger.emit_step(
                    iteration_id=iteration_id,
                    step=step,
                    status=LoopStatus.FAILED,
                    attempt=attempt,
                    duration_ms=duration_ms,
                    error_type=failure_type.value,
                )

                if not self._retry_policy.should_retry(failure_type, attempt):
                    raise

                self._record_state(iteration_id, step, LoopStatus.RETRY, attempt)
                self._loop_logger.emit_step(
                    iteration_id=iteration_id,
                    step=step,
                    status=LoopStatus.RETRY,
                    attempt=attempt,
                    duration_ms=0,
                    error_type=failure_type.value,
                )
                attempt += 1

    def _record_state(
        self,
        iteration_id: str,
        step: LoopStep,
        status: LoopStatus,
        attempt: int,
    ) -> None:
        self._state_history.append(
            LoopState(
                iteration_id=iteration_id,
                step=step,
                status=status,
                attempt=attempt,
                timestamp=utc_timestamp(self._now_fn),
            )
        )

    def _plan(self, goal: str) -> _PlanContext:
        tasks = self._goal_to_tasks(goal)
        feedback_context = self._memory.get_feedback_context(task_id=self._last_iteration_id)
        if len(tasks) == 1:
            plan = plan_task(tasks[0], context=feedback_context)
        else:
            plan = build_execution_plan(tasks)
        planned_adaptations = self._collect_planned_adaptations(plan)
        resolved_adaptations = self._conflict_resolver.resolve(planned_adaptations)
        return _PlanContext(
            plan=plan,
            resolved_adaptation_count=len(resolved_adaptations),
        )

    def _execute(self, plan) -> ExecutionReport:
        return run_plan(plan)

    def _validate(
        self,
        execution_report: ExecutionReport,
    ) -> tuple[dict[str, Any], str, EvaluationResult, FeedbackSignal]:
        metrics = self._extract_metrics(execution_report)
        status = self._classify(metrics)
        evaluation_result = self._evaluate(
            execution_report=execution_report,
            status=status,
        )
        feedback_signal = self._feedback_engine.generate_feedback(
            execution=execution_report,
            evaluation=evaluation_result,
        )
        self._route_feedback_to_adaptation_inputs(feedback_signal)
        return metrics, status, evaluation_result, feedback_signal

    def _evaluate(self, execution_report: ExecutionReport, status: str) -> EvaluationResult:
        total = max(int(execution_report.total_tasks), 0)
        completed = max(int(execution_report.completed_tasks), 0)
        failed = max(int(execution_report.failed_tasks), 0)
        skipped = max(int(execution_report.skipped_tasks), 0)

        if total == 0:
            score = 1.0
            match_type = "no_tasks"
        else:
            score = completed / total
            match_type = "exact" if failed == 0 and skipped == 0 else "failure"

        feedback = {
            SUCCESS: "Execution meets expected outcome.",
            PARTIAL: "Execution partially met expected outcome.",
            FAILURE: "Execution did not meet expected outcome.",
        }[status]

        return EvaluationResult(
            task_id=self._last_iteration_id,
            success=status == SUCCESS,
            score=round(score, 4),
            feedback=feedback,
            metrics={
                "status": status,
                "completed_tasks": completed,
                "failed_tasks": failed,
                "skipped_tasks": skipped,
                "total_tasks": total,
                "match_type": match_type,
            },
        )

    def _route_feedback_to_adaptation_inputs(self, feedback_signal: FeedbackSignal) -> None:
        self._memory.log_decision(
            decision="feedback_signal",
            reason="evaluation_to_feedback_mapping",
            context={
                "execution_id": feedback_signal.execution_id,
                "score": feedback_signal.score,
                "success": feedback_signal.success,
                "failure_type": feedback_signal.failure_type,
                "improvement_suggestions": list(feedback_signal.improvement_suggestions),
                "confidence": feedback_signal.confidence,
                "timestamp": feedback_signal.timestamp.isoformat(),
            },
        )

        if not feedback_signal.success and feedback_signal.failure_type:
            self._memory.log_failure(
                source="feedback_engine",
                error=feedback_signal.failure_type,
                context={
                    "execution_id": feedback_signal.execution_id,
                    "score": feedback_signal.score,
                    "suggestions": list(feedback_signal.improvement_suggestions),
                },
            )

    def _reflect_step(
        self,
        *,
        goal: str,
        plan,
        metrics: dict[str, Any],
        evaluation_result: EvaluationResult,
        feedback_signal: FeedbackSignal,
        status: str,
        resolved_adaptation_count: int,
    ) -> ReflectionResult:
        reflection = self._reflect(metrics)
        self._persist(
            goal,
            plan,
            metrics,
            evaluation_result,
            feedback_signal,
            reflection,
            status,
            resolved_adaptation_count=resolved_adaptation_count,
        )
        self._run_self_improvement(goal, metrics, reflection, status)
        return reflection

    def _goal_to_tasks(self, goal: str) -> list[dict]:
        return [
            {
                "id": "task-1",
                "description": goal,
                "dependencies": [],
            }
        ]

    def _extract_metrics(self, execution_report: ExecutionReport) -> dict[str, Any]:
        tasks = getattr(execution_report, "tasks", [])
        if tasks is None:
            tasks = []

        return {
            "total": execution_report.total_tasks,
            "completed": execution_report.completed_tasks,
            "failed": execution_report.failed_tasks,
            "skipped": execution_report.skipped_tasks,
            "tasks": tasks,
        }

    def _classify(self, metrics: dict[str, Any]) -> str:
        total = int(metrics["total"])
        completed = int(metrics["completed"])
        failed = int(metrics["failed"])
        skipped = int(metrics["skipped"])

        if total == 0:
            return SUCCESS

        if failed == 0 and skipped == 0:
            return SUCCESS

        if completed == 0:
            return FAILURE

        return PARTIAL

    def _reflect(self, metrics: dict[str, Any]) -> ReflectionResult:
        tasks: list[ExecutionTask] = list(metrics["tasks"])
        failed_tasks = [
            task.id
            for task in tasks
            if task.status in {ExecutionStatus.FAILED, ExecutionStatus.SKIPPED}
        ]

        total_tasks = int(metrics["total"])
        completed_tasks = int(metrics["completed"])
        success_rate = completed_tasks / total_tasks if total_tasks > 0 else 1.0

        if not failed_tasks:
            notes = "All tasks succeeded"
        elif completed_tasks > 0:
            notes = "Partial failure detected"
        else:
            notes = "Execution failed"

        return ReflectionResult(
            failed_tasks=failed_tasks,
            success_rate=success_rate,
            notes=notes,
        )

    def _persist(
        self,
        goal: str,
        plan,
        metrics: dict[str, Any],
        evaluation_result: EvaluationResult,
        feedback_signal: FeedbackSignal,
        reflection: ReflectionResult,
        status: str,
        resolved_adaptation_count: int,
    ) -> None:
        tasks: list[ExecutionTask] = list(metrics["tasks"])
        task_errors = [
            str(task.error or task.skip_reason)
            for task in tasks
            if task.status in {ExecutionStatus.FAILED, ExecutionStatus.SKIPPED}
            and (task.error or task.skip_reason)
        ]

        self._memory.record_execution(
            task_id=self.deterministic_iteration_id(goal),
            input={"goal": goal},
            plan={
                "task_ids": [task.id for task in plan.ordered_tasks],
                "total_tasks": len(plan.ordered_tasks),
            },
            result={
                "status": status,
                "total_tasks": int(metrics["total"]),
                "completed_tasks": int(metrics["completed"]),
                "failed_tasks": int(metrics["failed"]),
                "skipped_tasks": int(metrics["skipped"]),
            },
            success=status == SUCCESS,
            errors=task_errors,
            metadata={
                "source": "agent_loop",
                "resolved_adaptations": resolved_adaptation_count,
                "feedback": {
                    "execution_id": feedback_signal.execution_id,
                    "score": feedback_signal.score,
                    "success": feedback_signal.success,
                    "failure_type": feedback_signal.failure_type,
                    "improvement_suggestions": list(feedback_signal.improvement_suggestions),
                    "confidence": feedback_signal.confidence,
                    "timestamp": feedback_signal.timestamp.isoformat(),
                },
                "evaluation": {
                    "task_id": evaluation_result.task_id,
                    "success": evaluation_result.success,
                    "score": evaluation_result.score,
                    "feedback": evaluation_result.feedback,
                    "metrics": dict(evaluation_result.metrics),
                },
            },
        )

        self._memory.log_execution(
            status=status,
            total_tasks=int(metrics["total"]),
            completed_tasks=int(metrics["completed"]),
            failed_tasks=int(metrics["failed"]),
            skipped_tasks=int(metrics["skipped"]),
            metadata={
                "goal": goal,
                "plan": {
                    "task_ids": [task.id for task in plan.ordered_tasks],
                    "total_tasks": len(plan.ordered_tasks),
                },
                "resolved_adaptations": resolved_adaptation_count,
                "reflection": reflection.model_dump(),
            },
        )

        for task in tasks:
            self._memory.log_task(
                task_id=task.id,
                status=task.status.value,
                output=task.output,
                error=task.error,
                skip_reason=task.skip_reason,
            )

            if task.status in {ExecutionStatus.FAILED, ExecutionStatus.SKIPPED}:
                self._memory.log_failure(
                    source="agent_loop",
                    error=task.error or task.skip_reason or "unknown",
                    context={
                        "goal": goal,
                        "task_id": task.id,
                        "status": task.status.value,
                    },
                )

        self._memory.log_decision(
            decision=status,
            reason=reflection.notes,
            context={
                "goal": goal,
                "failed_tasks": reflection.failed_tasks,
                "success_rate": reflection.success_rate,
            },
        )

    def _run_self_improvement(
        self,
        goal: str,
        metrics: dict[str, Any],
        reflection: ReflectionResult,
        status: str,
    ) -> None:
        _ = metrics
        _ = reflection
        _ = status
        if self._self_improvement is None:
            return
        try:
            self._self_improvement.run(self._memory)
        except Exception as exc:
            failure_type = classify_failure(exc)
            if failure_type == FailureType.TRANSIENT:
                return
            raise

    def _collect_planned_adaptations(self, plan) -> list[Adaptation]:
        metadata = getattr(plan, "metadata", None)
        raw_adaptations = getattr(metadata, "adaptations", None)
        if not isinstance(raw_adaptations, list):
            return []

        collected: list[Adaptation] = []
        for item in raw_adaptations:
            if isinstance(item, Adaptation):
                collected.append(item)
                continue
            if isinstance(item, dict):
                try:
                    collected.append(Adaptation.model_validate(item))
                except Exception:
                    continue
        return collected