"""Structured event logging for Agent 14/15 self-improvement pipeline."""

from __future__ import annotations

from app.core.logger import get_logger

# Agent 14 events
SELF_IMPROVEMENT_STARTED = "SELF_IMPROVEMENT_STARTED"
EVALUATION_COMPLETED = "EVALUATION_COMPLETED"
OPTIMIZATION_GENERATED = "OPTIMIZATION_GENERATED"
POLICY_FILTER_APPLIED = "POLICY_FILTER_APPLIED"
IMPROVEMENTS_APPROVED = "IMPROVEMENTS_APPROVED"
SELF_IMPROVEMENT_COMPLETED = "SELF_IMPROVEMENT_COMPLETED"

# Agent 15 events
LOOP_STARTED = "LOOP_STARTED"
ANALYSIS_COMPLETED = "ANALYSIS_COMPLETED"
PATTERNS_DETECTED = "PATTERNS_DETECTED"
ADAPTATIONS_GENERATED = "ADAPTATIONS_GENERATED"
POLICY_VALIDATED = "POLICY_VALIDATED"
ADAPTATIONS_APPROVED = "ADAPTATIONS_APPROVED"
LOOP_COMPLETED = "LOOP_COMPLETED"


logger = get_logger(__name__)


def log_event(event: str, data: dict) -> None:
    """Emit structured deterministic event logs for the pipeline."""
    logger.info(event, data)
